#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/common.sh"

# 初始化 Miniforge 环境
log_info "Initializing conda..."

# Miniforge 安装路径
# export MAMBA_ROOT_PREFIX=/opt/Miniforge

# 初始化 Miniforge 环境
# export PATH=${MAMBA_ROOT_PREFIX}/bin:${PATH}
# 某些 linux 系统可能需要导入 Miniforge 的 lib 环境
# 如果你需要这个，就执行，之后可能还需要手动写入到 bash 或 zsh 的配置文件中，以持续生效
# 但是我不确定是不是所有的 linux 都会 lib 缺失，先注释吧
#export LD_LIBRARY_PATH=${MAMBA_ROOT_PREFIX}/lib:${LD_LIBRARY_PATH}

# 指定 python 版本
#export PY_VERSION=3.12.10
#export CONDA_PY_ENV=py${PY_VERSION}

# 配置 locale
# export LANGUAGE=zh_CN.UTF-8
# export LC_ALL=zh_CN.UTF-8
# export LANG=zh_CN.UTF-8
# export LC_CTYPE=zh_CN.UTF-8

# jbang 环境
# export PATH="${HOME}/.jbang/bin:${PATH}"
# java 环境
# export JAVA_HOME=${HOME}/.jbang/currentjdk
# export CLASSPATH=.:${JAVA_HOME}/lib
# export PATH=${PATH}:${JAVA_HOME}/bin

# 将日志输出重定向到日志文件
LOG_DIRS="/notebook/log"
SUPERCRONIC_LOG_FILE="${LOG_DIRS}/supercronic.log"
JUPYTER_LOG_FILE="${LOG_DIRS}/jupyter_startup.log"

# ================================================================
# 【修改1】系统任务和用户任务彻底分离
#   - SYSTEM_CRONTAB: 镜像内固定路径，每次启动重新生成，用户不需要动
#   - CRONTAB_FILE:   挂载卷里的用户任务文件，用户自己维护
# ================================================================
SYSTEM_CRONTAB='/etc/supercronic/system.crontab'
CRONTAB_FILE='/notebook/crontab.txt'

if [ ! -d "${LOG_DIRS}" ]; then
  mkdir -pv $LOG_DIRS
fi

exec > >(tee "${JUPYTER_LOG_FILE}") 2>&1

# 激活${CONDA_PY_ENV}
log_info "Activate ${CONDA_PY_ENV} env..."
# 明确激活 ${CONDA_PY_ENV}，确保非交互式环境变量生效，规避 ADDR2LINE: unbound variable
# 取消 set -u（如果你之前开启了严格模式）
set +u
# source conda 环境
. "${MAMBA_ROOT_PREFIX}/etc/profile.d/conda.sh"
conda activate "${CONDA_PY_ENV}"
set -u

log_info "Starting JupyterLab service..."

if [ ! -d "/notebook" ]; then
  log_error "/notebook directory does not exist. Please check volume mounts."
  exit 1
fi

for cmd in mamba jupyter-lab; do
  if ! command_exists "${cmd}"; then
    log_error "${cmd} is not installed. Aborting."
    exit 1
  fi
done

# --------- 开始统一修改 jupyter_server_config.py ---------

# 确保配置文件目录存在
mkdir -p "${HOME}/.jupyter"

# 【关键点 1】防止 Null Bytes：如果文件损坏(包含 \0)，则直接删除重来
if [ -f "${HOME}/.jupyter/jupyter_server_config.py" ]; then
    if grep -qP '\x00' "${HOME}/.jupyter/jupyter_server_config.py" 2>/dev/null; then
        log_warning "Detected NULL bytes in config file, removing corrupted file..."
        rm -f "${HOME}/.jupyter/jupyter_server_config.py"
    fi
fi

# 如配置文件不存在则生成 jupyter_server_config.py
if [ ! -f "${HOME}/.jupyter/jupyter_server_config.py" ]; then
    log_info "Generating Jupyter server configuration..."
    jupyter-server --generate-config -y
fi

# 设置密码：如果JUPYTER_PASSWORD变量未设置，则采用默认值
if [[ -z "${JUPYTER_PASSWORD:-}" ]]; then
    log_warning "JUPYTER_PASSWORD variable not set, using default value: 123456"
    export JUPYTER_PASSWORD=123456
fi

# 生成密码哈希（新版Jupyter使用 Notebook.auth 模块产生密码哈希）
# JUPYTER_PASSWORD_HASH=$(python -c "from notebook.auth import passwd; print(passwd('${JUPYTER_PASSWORD}'))")
JUPYTER_PASSWORD_HASH=$(python -c "
try:
    from jupyter_server.auth.security import passwd
except ImportError:
    from notebook.auth import passwd
print(passwd('${JUPYTER_PASSWORD}'))
")

log_info "Appending custom configuration for default shell and JUPYTER_PASSWORD to Jupyter server config..."

# 将 Terminal 默认 shell 和密码写入 jupyter_server_config.py
# 【关键点 2】使用新版配置项并采用“先清空再写入”或“精准替换”
# 这样能保证每次重启，配置都是干净且符合最新标准的
cat <<af5ab649831964 | tee "${HOME}/.jupyter/jupyter_server_config.py"
# Generated by startup script on $(date)
c.ServerApp.terminado_settings = {'shell_command': ['/bin/bash']}
c.ServerApp.ip = '0.0.0.0'
c.ServerApp.open_browser = False
c.ServerApp.allow_root = True

# 解决 Deprecated 警告，同时兼容新旧版本
c.PasswordIdentityProvider.hashed_password = "${JUPYTER_PASSWORD_HASH}"
# 为了极致兼容，可以保留下面这行，或者只用上面那行（推荐只用上面的）
# c.ServerApp.password = "${JUPYTER_PASSWORD_HASH}"
af5ab649831964

log_info "Jupyter server configuration updated at ${HOME}/.jupyter/jupyter_server_config.py"

# 【关键点 3】最后校验一次文件完整性，防止写入异常
if [ ! -s "${HOME}/.jupyter/jupyter_server_config.py" ]; then
    log_error "Config file is empty or failed to write!"
    exit 1
fi

log_info "Jupyter configuration verified."

# 设置默认主题为 JupyterLab Dark High Contrast
mkdir -p "${HOME}/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/"
cat <<'af5ab649831964' | tee "${HOME}/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings"
{
    "theme": "JupyterLab Dark High Contrast"
}
af5ab649831964
log_info "Default JupyterLab theme set to 'JupyterLab Dark'."

# ================================================================
# 【修改2】生成系统级 crontab（每次启动重新生成，保证最新）
#   原来的做法是追加到用户的 crontab.txt，用 # SUPERCRONIC_TASK
#   标记判重，逻辑脆弱且容易被 inotifywait 误触发。
#   现在改为写入镜像内固定路径，与用户文件完全隔离。
# ================================================================
log_info "生成系统级 crontab: ${SYSTEM_CRONTAB}"
mkdir -p "$(dirname "${SYSTEM_CRONTAB}")"
cat > "${SYSTEM_CRONTAB}" << af5ab649831964
# 系统任务，由镜像启动脚本自动生成，请勿手动修改
# 如需添加自定义任务，请编辑 ${CRONTAB_FILE}

# 每天记录 supercronic 心跳
0 0 * * * echo "\$(date) supercronic job ran" >> "${JUPYTER_LOG_FILE}"
0 0 * * * echo "\$(date) supercronic job ran" >> "${SUPERCRONIC_LOG_FILE}"
# 每天凌晨1点裁剪日志，防止无限膨胀
0 1 * * * tail -n 1000 "${SUPERCRONIC_LOG_FILE}" > "${SUPERCRONIC_LOG_FILE}.tmp" && mv "${SUPERCRONIC_LOG_FILE}.tmp" "${SUPERCRONIC_LOG_FILE}"
0 1 * * * tail -n 1000 "${JUPYTER_LOG_FILE}" > "${JUPYTER_LOG_FILE}.tmp" && mv "${JUPYTER_LOG_FILE}.tmp" "${JUPYTER_LOG_FILE}"
af5ab649831964
log_info "系统级 crontab 已生成"

# ================================================================
# 【修改3】用户 crontab 不存在时创建空文件（不再写入系统任务）
#   用户只需在 crontab.txt 里写自己的任务即可，例如：
#   0 7 * * * cd /notebook && /bin/bash ./run-test.sh > ./log/run-test.log 2>&1
# ================================================================
if [ ! -f "${CRONTAB_FILE}" ]; then
  log_info "用户 crontab 文件不存在，创建空文件: ${CRONTAB_FILE}"
  cat > "${CRONTAB_FILE}" << 'af5ab649831964'
# 用户自定义 cron 任务，修改此文件后会自动热重载，无需重启容器
# 示例（每天07:00运行爬虫脚本）：
# 0 7 * * * cd /notebook && /bin/bash ./run-test.sh > ./log/run-test.log 2>&1
af5ab649831964
fi

if command -v supercronic > /dev/null; then
  # ==============================================================
  # 【修改4】supercronic 只接受单个文件，所以先合并再启动
  #   - MERGED_CRONTAB 是临时合并文件，每次重载都重新生成
  #   - 不再使用 tee 管道，避免热重载时 tee 进程泄漏
  #   - 用 /tmp/supercronic.pid 记录 pid，方便精准杀进程
  # ==============================================================
  MERGED_CRONTAB='/tmp/supercronic_merged.crontab'
  cat "${SYSTEM_CRONTAB}" "${CRONTAB_FILE}" > "${MERGED_CRONTAB}"

  log_info "Starting supercronic with merged crontab"
  supercronic "${MERGED_CRONTAB}" >> "${SUPERCRONIC_LOG_FILE}" 2>&1 &
  echo $! > /tmp/supercronic.pid
  log_info "supercronic started (pid $(cat /tmp/supercronic.pid))"

  if command -v inotifywait >/dev/null; then
    # ============================================================
    # 【修改5】inotifywait 只监听用户文件，加 md5 防误触发
    #   原来的问题：
    #     - 监听 crontab.txt，同目录写日志产生 spurious 事件
    #     - 没有内容校验，文件没变也会重启 supercronic
    #     - 重启时只杀 supercronic，tee 进程泄漏
    #   现在的改动：
    #     - md5 校验，内容真正变了才重启
    #     - 重新合并后再重启，保证 system 任务始终在
    #     - pid 文件精准 kill，不误杀其他进程
    # ============================================================
    (
      _cron_hash=$(md5sum "${CRONTAB_FILE}" | awk '{print $1}')
      while true; do
        inotifywait -e modify "${CRONTAB_FILE}"
        _new_hash=$(md5sum "${CRONTAB_FILE}" | awk '{print $1}')
        if [ "${_new_hash}" != "${_cron_hash}" ]; then
          _cron_hash="${_new_hash}"
          log_info "用户 crontab 内容已变更，重新合并并重启 supercronic..."
          cat "${SYSTEM_CRONTAB}" "${CRONTAB_FILE}" > "${MERGED_CRONTAB}"
          kill "$(cat /tmp/supercronic.pid)" 2>/dev/null || true
          supercronic "${MERGED_CRONTAB}" >> "${SUPERCRONIC_LOG_FILE}" 2>&1 &
          echo $! > /tmp/supercronic.pid
          log_info "supercronic 已重启 (pid $(cat /tmp/supercronic.pid))"
        else
          log_info "inotify 事件触发但 crontab 内容未变（spurious event），忽略"
        fi
      done
    ) &
  else
    log_warning "inotifywait not found, skipping crontab auto-reload"
  fi
else
  log_warning "Cannot find supercronic. supercronic will not run."
fi

# --------- 启动 JupyterLab ---------
log_info "Launching JupyterLab on port 8888..."
jupyter-lab --allow-root --no-browser --notebook-dir=/notebook --ip=0.0.0.0 --port=8888